// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJW0w-25X05R-JWUVRG-hGjJKr7rpkJ4E',
    appId: '1:880941815126:web:4ff097e14f3ab4554272f7',
    messagingSenderId: '880941815126',
    projectId: 'syncobackend',
    authDomain: 'syncobackend.firebaseapp.com',
    storageBucket: 'syncobackend.firebasestorage.app',
    measurementId: 'G-VFM403NQEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE8DaQA5tnv9IjpMRN6Xn9r9rOWbC7Hd8',
    appId: '1:880941815126:android:8052fe1f5ebd1f3b4272f7',
    messagingSenderId: '880941815126',
    projectId: 'syncobackend',
    storageBucket: 'syncobackend.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtR6uqpe3U1AZJgB7MWPkmwCg7hZhVDGU',
    appId: '1:880941815126:ios:cc665b220556a8cf4272f7',
    messagingSenderId: '880941815126',
    projectId: 'syncobackend',
    storageBucket: 'syncobackend.firebasestorage.app',
    iosClientId: '880941815126-vph3ioee3opso6o3idv1f0lcimrcc2sl.apps.googleusercontent.com',
    iosBundleId: 'com.hersync.app.hersync',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtR6uqpe3U1AZJgB7MWPkmwCg7hZhVDGU',
    appId: '1:880941815126:ios:cc665b220556a8cf4272f7',
    messagingSenderId: '880941815126',
    projectId: 'syncobackend',
    storageBucket: 'syncobackend.firebasestorage.app',
    iosClientId: '880941815126-vph3ioee3opso6o3idv1f0lcimrcc2sl.apps.googleusercontent.com',
    iosBundleId: 'com.hersync.app.hersync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJW0w-25X05R-JWUVRG-hGjJKr7rpkJ4E',
    appId: '1:880941815126:web:bdc349c01a2945ea4272f7',
    messagingSenderId: '880941815126',
    projectId: 'syncobackend',
    authDomain: 'syncobackend.firebaseapp.com',
    storageBucket: 'syncobackend.firebasestorage.app',
    measurementId: 'G-K5T0KFH61S',
  );
}
