// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC0xPkj3WBMl11wR3L1lpD9C7RQpWplpI',
    appId: '1:510590899188:web:b0ec18252cebf323ffdfa1',
    messagingSenderId: '510590899188',
    projectId: 'synco-75c06',
    authDomain: 'synco-75c06.firebaseapp.com',
    storageBucket: 'synco-75c06.firebasestorage.app',
    measurementId: 'G-6R9PKC3LRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8cVAOaa0Eg29UfbUbWyBKoJFJ0oGrdgk',
    appId: '1:510590899188:android:7b0c7885e4a2f0efffdfa1',
    messagingSenderId: '510590899188',
    projectId: 'synco-75c06',
    storageBucket: 'synco-75c06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAovHBgU_q7pid-2SoD4rmhLDcieHfUgPI',
    appId: '1:510590899188:ios:de05fcf548aa8078ffdfa1',
    messagingSenderId: '510590899188',
    projectId: 'synco-75c06',
    storageBucket: 'synco-75c06.firebasestorage.app',
    iosBundleId: 'com.hersync.app.hersync',
  );
}
