/// Data model for the generated SYNCO health report.
///
/// A [HealthReportData] is a plain, serialisation-friendly snapshot of the
/// user's stored health information for a selected period. It is built by
/// [HealthReportService.buildReport] from the app's existing providers and is
/// rendered to PDF by `HealthReportPdfGenerator`.
///
/// Only the authenticated user's own data is ever placed in this model.
library;

/// The reporting window the user can choose from.
enum HealthReportPeriodType { weekly, monthly }

/// One row of the score breakdown (mirrors the Full Health Report screen).
class ScoreBreakdownRow {
  final String title;
  final String value;
  final String statusLabel;
  final int statusColorArgb;

  const ScoreBreakdownRow({
    required this.title,
    required this.value,
    required this.statusLabel,
    required this.statusColorArgb,
  });
}

/// One health tracker section shown under "Health Tracking".
///
/// Only trackers that actually contain data in the period are included.
class TrackingSection {
  final String title;
  final String summary;
  final List<String> details;

  const TrackingSection({
    required this.title,
    required this.summary,
    this.details = const [],
  });
}

/// A completed symptom screening assessment (PCOS / Endometriosis / Fibroids).
class AssessmentReportData {
  final String title;
  final String scoreLabel;
  final String levelLabel;
  final String completedLabel;

  const AssessmentReportData({
    required this.title,
    required this.scoreLabel,
    required this.levelLabel,
    required this.completedLabel,
  });
}

/// An existing AI insight generated by SYNCO for the user's own data.
class AiInsightReportData {
  final String kindLabel;
  final String categoryLabel;
  final String title;
  final String summary;
  final String? detail;
  final String periodLabel;
  final String basisLabel;

  const AiInsightReportData({
    required this.kindLabel,
    required this.categoryLabel,
    required this.title,
    required this.summary,
    this.detail,
    required this.periodLabel,
    required this.basisLabel,
  });
}

/// Period & cycle section (estimates clearly labelled as predictions).
class CycleReportData {
  final bool hasHistory;
  final int averageCycleLength;
  final int averagePeriodDuration;
  final DateTime? lastPeriodStartDate;
  final String currentPhaseLabel;
  final int currentDayOfCycle;
  final DateTime? predictedNextPeriod;
  final int? daysUntilNextPeriod;
  final DateTime? estimatedOvulation;
  final DateTime? fertileWindowStart;
  final DateTime? fertileWindowEnd;
  final int cycleNumber;

  /// Human-readable lines for periods logged inside the report period.
  final List<String> periodHistoryLines;

  const CycleReportData({
    required this.hasHistory,
    required this.averageCycleLength,
    required this.averagePeriodDuration,
    this.lastPeriodStartDate,
    required this.currentPhaseLabel,
    required this.currentDayOfCycle,
    this.predictedNextPeriod,
    this.daysUntilNextPeriod,
    this.estimatedOvulation,
    this.fertileWindowStart,
    this.fertileWindowEnd,
    required this.cycleNumber,
    this.periodHistoryLines = const [],
  });
}

/// The complete snapshot used to generate one health report PDF.
class HealthReportData {
  final HealthReportPeriodType periodType;

  /// Label such as "Weekly Health Report".
  final String periodLabel;

  /// Label such as "10 Aug 2026 – 16 Aug 2026" or "August 2026".
  final String dateRangeLabel;

  final DateTime startDate;
  final DateTime endDate;
  final DateTime generatedAt;

  /// Display name for the authenticated user, when available.
  final String userName;

  // 1. Health overview
  final int healthScore;
  final int percentile;
  final String healthStatus;
  final String healthMessage;
  final int healthColorArgb;

  // 2. Score breakdown
  final List<ScoreBreakdownRow> breakdown;

  // 3. Health tracking
  final List<TrackingSection> tracking;

  // 4. Period & cycle
  final CycleReportData cycle;

  // 5. Symptom assessments
  final List<AssessmentReportData> assessments;

  // 6. AI insights
  final List<AiInsightReportData> insights;

  // 7. Health summary
  final String summaryNote;

  const HealthReportData({
    required this.periodType,
    required this.periodLabel,
    required this.dateRangeLabel,
    required this.startDate,
    required this.endDate,
    required this.generatedAt,
    required this.userName,
    required this.healthScore,
    required this.percentile,
    required this.healthStatus,
    required this.healthMessage,
    required this.healthColorArgb,
    required this.breakdown,
    required this.tracking,
    required this.cycle,
    required this.assessments,
    required this.insights,
    required this.summaryNote,
  });
}
